"""Shared bounds for on-demand durable flow detail."""

MAX_DURABLE_DETAIL_RETAINED_BODY_BYTES = 1024 * 1024
MAX_DURABLE_DETAIL_MESSAGES = 512
MAX_DURABLE_DETAIL_OUTPUT_BYTES = 4 * 1024 * 1024

__all__ = [
    "MAX_DURABLE_DETAIL_MESSAGES",
    "MAX_DURABLE_DETAIL_OUTPUT_BYTES",
    "MAX_DURABLE_DETAIL_RETAINED_BODY_BYTES",
]
